# Generated by Django 3.2.7 on 2021-09-07 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_data_mahasiswa_jenisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.pekerjaan')),
            ],
        ),
        migrations.AddField(
            model_name='data_mahasiswa',
            name='pekerjaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.pekerjaan'),
        ),
        migrations.AddField(
            model_name='data_mahasiswa',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.unit'),
        ),
    ]
