# Generated by Django 3.2.7 on 2021-09-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210907_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_mahasiswa',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
