# Generated by Django 3.2.7 on 2021-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_data_mahasiswa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_mahasiswa',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
